const fs = require('fs');
const https = require('https');

// Load parsed table entries
const tableEntries = JSON.parse(fs.readFileSync('src/data/wikipediaTableEntries.json', 'utf8'));

// Helper to fetch summary from Wikipedia REST API with timeout
function fetchSummary(title) {
  return new Promise((resolve) => {
    const encoded = encodeURIComponent(title.replace(/\s+/g, '_'));
    const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${encoded}`;
    const req = https.get(url, {
      headers: { 'User-Agent': 'AfricaliaGenealogyTree/1.0 (educational; research; contact: zeluisfp@gmail.com)' },
      timeout: 5000
    }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode === 200) {
          try {
            const j = JSON.parse(data);
            resolve({
              extract: j.extract || '',
              thumbnail: j.thumbnail?.source || null,
              description: j.description || '',
              url: j.content_urls?.desktop?.page || `https://en.wikipedia.org/wiki/${encoded}`,
              canonicalTitle: j.title || title
            });
          } catch(e) { resolve(null); }
        } else {
          resolve(null);
        }
      });
    });
    req.on('error', () => resolve(null));
    req.on('timeout', () => { req.destroy(); resolve(null); });
  });
}

// Priority list of African ethnic groups for pre-caching
const priorityArticles = [
  'Yoruba people', 'Igbo people', 'Hausa people', 'Edo people', 'Ibibio people', 'Tiv people', 'Fula people', 'Kanuri people',
  'Akan people', 'Ashanti people', 'Ewe people', 'Ga-Adangbe people', 'Fante people', 'Fon people', 'Mina people',
  'Wolof people', 'Mandinka people', 'Serer people', 'Jola people', 'Balanta people', 'Fula people',
  'Mende people', 'Temne people', 'Kpelle people', 'Bassa people', 'Kru people', 'Dan people',
  'Kongo people', 'Mbundu people', 'Ovimbundu people', 'Chokwe people', 'Bakongo', 'Teke people', 'Fang people', 'Bateke',
  'Mongo people', 'Luba people', 'Lunda people', 'Mangbetu people', 'Zande people', 'Kuba Kingdom',
  'Oromo people', 'Amhara people', 'Tigrayans', 'Somali people', 'Afar people', 'Sidama people', 'Gurage people',
  'Kikuyu people', 'Luhya people', 'Luo people', 'Kalenjin people', 'Kamba people', 'Kisii people', 'Maasai people',
  'Sukuma people', 'Chagga people', 'Haya people', 'Nyamwezi people', 'Hehe people', 'Makonde people',
  'Zulu people', 'Xhosa people', 'Sotho people', 'Tswana people', 'Venda people', 'Tsonga people', 'Swazi people',
  'Shona people', 'Northern Ndebele people', 'Chewa people', 'Tumbuka people', 'Bemba people', 'Tonga people',
  'San peoples', 'Nama people', 'Khoikhoi', 'Herero people', 'Ovambo people', 'Damara people',
  'Tuareg people', 'Berbers', 'Songhai people', 'Bambara people', 'Dogon people', 'Mossi people', 'Gurma people',
  'Dinka people', 'Nuer people', 'Shilluk people', 'Nubians', 'Beja people', 'Fur people'
];

async function run() {
  console.log(`Starting pre-cache fetch for ${priorityArticles.length} priority ethnic groups...`);
  const cache = {};
  
  // Fetch in batches of 5 to be polite to Wikipedia's API
  const batchSize = 5;
  for (let i = 0; i < priorityArticles.length; i += batchSize) {
    const batch = priorityArticles.slice(i, i + batchSize);
    const results = await Promise.all(batch.map(art => fetchSummary(art)));
    batch.forEach((art, idx) => {
      const res = results[idx];
      if (res) {
        cache[art] = res;
        console.log(`  ✓ ${art} (${res.extract ? res.extract.length : 0} chars)`);
      } else {
        console.log(`  ✗ ${art} (fetch missed)`);
      }
    });
  }

  console.log(`Successfully pre-cached ${Object.keys(cache).length} articles.`);
  fs.writeFileSync('src/data/wikipediaPreCache.json', JSON.stringify(cache, null, 2));

  // Now compile TypeScript module src/data/wikipediaEthnicAtlas.ts
  const tsContent = `// Autogenerated Wikipedia Cultural Atlas for Sovereign Africalia Ethnic Tree
// Sources:
// - Wikipedia: List of contemporary ethnic groups of Africa (https://en.wikipedia.org/wiki/List_of_contemporary_ethnic_groups_of_Africa)
// - Wikipedia REST API v1 (https://en.wikipedia.org/api/rest_v1/)

export interface WikipediaEthnicEntry {
  name: string;
  article: string;
  languages: string;
  homeland: string;
  subgroups: string;
  religion: string;
  extract?: string;
  thumbnail?: string | null;
  description?: string;
  url?: string;
}

export const WIKIPEDIA_TABLE_ENTRIES: WikipediaEthnicEntry[] = ${JSON.stringify(tableEntries, null, 2)};

export const WIKIPEDIA_PRE_CACHE: Record<string, {
  extract: string;
  thumbnail: string | null;
  description: string;
  url: string;
  canonicalTitle: string;
}> = ${JSON.stringify(cache, null, 2)};

// Normalize string for fuzzy key lookup
export function normalizeEthnicKey(name: string): string {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]/g, '');
}

// Built-in lookup map
const ENTRIES_BY_KEY = new Map<string, WikipediaEthnicEntry>();
for (const entry of WIKIPEDIA_TABLE_ENTRIES) {
  ENTRIES_BY_KEY.set(normalizeEthnicKey(entry.name), entry);
  const altKey = normalizeEthnicKey(entry.article.replace(/\\s+people.*$/i, ''));
  if (!ENTRIES_BY_KEY.has(altKey)) {
    ENTRIES_BY_KEY.set(altKey, entry);
  }
}

/**
 * Resolve Wikipedia metadata for an ethnic group name
 */
export function findWikipediaEntry(rawName: string): WikipediaEthnicEntry | null {
  if (!rawName) return null;
  const key = normalizeEthnicKey(rawName);

  // 1. Direct key match
  if (ENTRIES_BY_KEY.has(key)) {
    return enrichEntry(ENTRIES_BY_KEY.get(key)!);
  }

  // 2. Check compound parts (e.g. "Edo / Bini" -> "Edo", "Bini")
  const parts = rawName.split(/[\\/\\-()]/).map(s => s.trim()).filter(Boolean);
  for (const part of parts) {
    const partKey = normalizeEthnicKey(part);
    if (ENTRIES_BY_KEY.has(partKey)) {
      return enrichEntry(ENTRIES_BY_KEY.get(partKey)!);
    }
  }

  // 3. Partial substring search across known table entries
  for (const entry of WIKIPEDIA_TABLE_ENTRIES) {
    const entryKey = normalizeEthnicKey(entry.name);
    if (key.includes(entryKey) || entryKey.includes(key)) {
      return enrichEntry(entry);
    }
  }

  // 4. Fallback synthetic entry pointing to canonical Wikipedia article
  const cleanName = parts[0] || rawName;
  const canonicalArticle = cleanName.includes('people') ? cleanName : \`\${cleanName} people\`;
  const cached = WIKIPEDIA_PRE_CACHE[canonicalArticle] || WIKIPEDIA_PRE_CACHE[cleanName];

  return {
    name: cleanName,
    article: canonicalArticle,
    languages: 'African Linguistic Family',
    homeland: 'Historical African Homeland',
    subgroups: '',
    religion: 'Traditional African Traditions & Contemporary Faiths',
    extract: cached?.extract,
    thumbnail: cached?.thumbnail,
    description: cached?.description,
    url: cached?.url || \`https://en.wikipedia.org/wiki/\${encodeURIComponent(canonicalArticle.replace(/\\s+/g, '_'))}\`
  };
}

function enrichEntry(entry: WikipediaEthnicEntry): WikipediaEthnicEntry {
  const cached = WIKIPEDIA_PRE_CACHE[entry.article] || WIKIPEDIA_PRE_CACHE[\`\${entry.name} people\`] || WIKIPEDIA_PRE_CACHE[entry.name];
  return {
    ...entry,
    extract: cached?.extract || entry.extract,
    thumbnail: cached?.thumbnail !== undefined ? cached.thumbnail : entry.thumbnail,
    description: cached?.description || entry.description,
    url: cached?.url || entry.url || \`https://en.wikipedia.org/wiki/\${encodeURIComponent(entry.article.replace(/\\s+/g, '_'))}\`
  };
}
`;

  fs.writeFileSync('src/data/wikipediaEthnicAtlas.ts', tsContent);
  console.log('Successfully generated src/data/wikipediaEthnicAtlas.ts!');
}

run();
